name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust region as necessary

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t myconsoleapp:latest .
          docker tag myconsoleapp:latest ${{ steps.ecr-login.outputs.registry }}/myconsoleapp:latest
          docker tag myconsoleapp:latest ${{ steps.ecr-login.outputs.registry }}/myconsoleapp:${{ github.sha }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.ecr-login.outputs.registry }}/myconsoleapp:latest
          docker push ${{ steps.ecr-login.outputs.registry }}/myconsoleapp:${{ github.sha }}
